# dbt Project Configuration
# https://docs.getdbt.com/reference/dbt_project.yml

name: 'electrostore_dbt'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# Profile is defined in ~/.dbt/profiles.yml
profile: 'dbt_debby'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  electrostore_dbt:
    # Default materialization for all models
    +materialized: view
    +as_columnstore: False

    # Staging models configuration
    staging:
      +materialized: view
      +schema: staging

    # Intermediate models configuration
    intermediate:
      +materialized: view
      +schema: intermediate

    # Mart models configuration
    mart:
      +materialized: table
      +schema: mart

# Configure seeds (CSV files)
seeds:
  electrostore_dbt:
    +schema: seeds
    +as_columnstore: False

# Configure snapshots
snapshots:
  electrostore_dbt:
    +target_schema: snapshots
    +as_columnstore: False
