dbt_debby:
  target: prod
  outputs:
    prod:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: "{{ env_var('DBT_SERVER') }}"
      port: "{{ env_var('DBT_PORT', '1433') | int }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'dbo') }}"
      authentication: sql
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      encrypt: true
      trust_cert: true
      login_timeout: 30
