version: 2

models:
  - name: dim_customers
    description: Customer dimension table containing all customer attributes
    columns:
      - name: customer_id
        description: Unique identifier for each customer
        tests:
          - unique
          - not_null
      - name: customer
        description: Anonymized customer identifier
      - name: email
        description: Customer email address
      - name: phone
        description: Customer phone number
      - name: customer_type
        description: Type/category of customer
      - name: region
        description: Geographic region of the customer
      - name: status
        description: Current status of the customer account
      - name: registration_date
        description: Date when customer registered
      - name: last_purchase_date
        description: Date of customer's most recent purchase

  - name: dim_products
    description: Product dimension table containing all product attributes and account manager assignments
    columns:
      - name: product_id
        description: Unique identifier for each product
        tests:
          - unique
          - not_null
      - name: product_name
        description: Name of the product
      - name: sku
        description: Stock keeping unit code
      - name: category
        description: Product category
      - name: subcategory
        description: Product subcategory
      - name: brand
        description: Product brand
      - name: unit_price
        description: Selling price per unit
      - name: cost
        description: Cost per unit
      - name: status
        description: Current product status
      - name: launch_date
        description: Date when product was launched
      - name: account_manager
        description: Account manager responsible for this product

  - name: dim_stores
    description: Store dimension table containing all store location and attribute information
    columns:
      - name: store_id
        description: Unique identifier for each store
        tests:
          - unique
          - not_null
      - name: store_name
        description: Name of the store
      - name: store_code
        description: Store code identifier
      - name: city
        description: City where store is located
      - name: state
        description: State where store is located
      - name: region
        description: Geographic region of the store
      - name: store_type
        description: Type/format of store
      - name: size_sqft
        description: Store size in square feet
      - name: status
        description: Current operational status of the store
      - name: open_date
        description: Date when store opened

  - name: dim_date
    description: Date dimension table with calendar attributes
    columns:
      - name: date_day
        description: The actual date value
        tests:
          - unique
          - not_null
      - name: year
        description: Four-digit year
      - name: quarter
        description: Quarter number (1-4)
      - name: month_number
        description: Month number (1-12)
      - name: month_name
        description: Full month name
      - name: week_of_year
        description: Week number within the year
      - name: day_of_month
        description: Day number within the month
      - name: day_of_week
        description: Day of week number
      - name: day_name
        description: Full day name
      - name: is_weekend
        description: Flag indicating if date is a weekend (1=yes, 0=no)

  - name: fact_sales
    description: Sales fact table containing all sales transaction details
    columns:
      - name: sale_id
        description: Unique identifier for each sale transaction
        tests:
          - unique
          - not_null
      - name: customer_id
        description: Foreign key to dim_customers
        tests:
          - not_null
      - name: product_id
        description: Foreign key to dim_products
        tests:
          - not_null
      - name: store_id
        description: Foreign key to dim_stores
        tests:
          - not_null
      - name: sale_date
        description: Date of the sale transaction
      - name: quantity
        description: Number of units sold
      - name: unit_price
        description: Price per unit at time of sale
      - name: discount_percent
        description: Discount percentage applied to sale
      - name: total_amount
        description: Total transaction amount

  - name: fact_inventory
    description: Inventory fact table containing current stock levels and reorder information
    columns:
      - name: inventory_id
        description: Unique identifier for each inventory record
        tests:
          - unique
          - not_null
      - name: product_id
        description: Foreign key to dim_products
        tests:
          - not_null
      - name: store_id
        description: Foreign key to dim_stores
        tests:
          - not_null
      - name: stock_level
        description: Current quantity in stock
      - name: reorder_point
        description: Stock level threshold for reordering
      - name: last_updated
        description: Timestamp of last inventory update
